# Generated by Django 6.0.3 on 2026-09-28 21:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0018_zoom_recording_transcripts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleState',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('locked_until', models.DateTimeField(null=True)),
                ('token', models.CharField(blank=True, max_length=36)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'callcenter_cycle_state',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('zoom_email', models.EmailField(max_length=254)),
                ('zoom_user_id', models.CharField(blank=True, max_length=128)),
                ('zoom_account', models.CharField(choices=[('student', 'Student'), ('office', 'Office')], max_length=16)),
                ('daily_talk_target_minutes', models.PositiveIntegerField(default=180)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'callcenter_agent',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('result', models.JSONField(default=dict)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.zoomphonerecording')),
            ],
            options={
                'db_table': 'callcenter_ai_analysis',
            },
        ),
        migrations.CreateModel(
            name='CallMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_email', models.EmailField(db_index=True, max_length=254)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callcenter.agent')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.zoomphonecall')),
            ],
            options={
                'db_table': 'callcenter_call_match',
            },
        ),
        migrations.CreateModel(
            name='CaseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('attendance', 'Attendance'), ('pr', 'PR'), ('mcm', 'MCM'), ('otj', 'OTJ'), ('epa', 'EPA'), ('reminder', 'Reminder'), ('satisfaction', 'Satisfaction')], db_index=True, max_length=20)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('reason_key', models.CharField(max_length=500, unique=True)),
                ('learner_email', models.EmailField(db_index=True, max_length=254)),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('coach', models.CharField(blank=True, max_length=255)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('programme', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('source_data', models.JSONField(default=dict)),
                ('risk', models.CharField(default='amber', max_length=10)),
                ('overdue_since', models.DateField(blank=True, null=True)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('booking_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_learner', 'Pending Learner'), ('pending_verification', 'Pending Verification'), ('ai_suggested_close', 'Ai Suggested Close'), ('resolved', 'Resolved'), ('unreachable', 'Unreachable'), ('escalated', 'Escalated')], db_index=True, default='new', max_length=30)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_actor', models.CharField(default='System', max_length=255)),
                ('last_action_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_option', models.CharField(blank=True, max_length=40)),
                ('resolved_by', models.CharField(blank=True, max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='callcenter.agent')),
                ('resolved_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='callcenter.agent')),
            ],
            options={
                'db_table': 'callcenter_case',
            },
        ),
        migrations.CreateModel(
            name='CaseCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_result', models.CharField(blank=True, max_length=32)),
                ('outcome', models.CharField(blank=True, max_length=30)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='callcenter.callmatch')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='callcenter.caseticket')),
            ],
            options={
                'db_table': 'callcenter_case_call',
            },
        ),
        migrations.CreateModel(
            name='CallIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_email', models.EmailField(db_index=True, max_length=254)),
                ('number', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callcenter.agent')),
                ('matched_call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.zoomphonecall')),
                ('tickets', models.ManyToManyField(related_name='intents', to='callcenter.caseticket')),
            ],
            options={
                'db_table': 'callcenter_call_intent',
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('kind', models.CharField(max_length=32)),
                ('mode', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('text', models.TextField()),
                ('cc', models.EmailField(blank=True, max_length=254)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='callcenter.caseticket')),
            ],
            options={
                'db_table': 'callcenter_email',
            },
        ),
        migrations.CreateModel(
            name='EmailQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'callcenter_email_quota',
                'constraints': [models.UniqueConstraint(fields=('recipient', 'day'), name='cc_email_daily_quota')],
            },
        ),
        migrations.CreateModel(
            name='EmployerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('quarter', models.CharField(max_length=7)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='survey', to='callcenter.caseticket')),
            ],
            options={
                'db_table': 'callcenter_satisfaction',
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('actor', models.CharField(default='System', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='callcenter.agent')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.zoomphonecall')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='callcenter.caseticket')),
            ],
            options={
                'db_table': 'callcenter_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('zoom_email'), models.F('zoom_account'), name='cc_agent_email_account'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('zoom_user_id', ''), _negated=True), fields=('zoom_user_id', 'zoom_account'), name='cc_agent_user_account'),
        ),
        migrations.AddConstraint(
            model_name='aianalysis',
            constraint=models.UniqueConstraint(fields=('recording', 'transcript_hash'), name='cc_ai_version_unique'),
        ),
        migrations.AddIndex(
            model_name='caseticket',
            index=models.Index(fields=['status', 'due_at'], name='cc_status_due'),
        ),
        migrations.AddConstraint(
            model_name='caseticket',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source_type', 'source_id'), name='cc_source_ticket_unique'),
        ),
        migrations.AddConstraint(
            model_name='casecall',
            constraint=models.UniqueConstraint(fields=('ticket', 'match'), name='cc_case_call_unique'),
        ),
        migrations.AddConstraint(
            model_name='employersatisfaction',
            constraint=models.UniqueConstraint(fields=('manager_email', 'quarter'), name='cc_survey_quarter_unique'),
        ),
        migrations.AddConstraint(
            model_name='employersatisfaction',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 5)), _connector='OR'), name='cc_survey_score_range'),
        ),
    ]
