# Generated by Django 6.0.3 on 2026-09-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseticket',
            name='evidence_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
