# Generated by Django 6.0.3 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_agent_zoom_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='zoom_account',
            field=models.CharField(choices=[('student', 'Student'), ('office', 'Accountant')], max_length=16),
        ),
    ]
