# Generated by Django 6.0.3 on 2026-06-11 13:34

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_progressreviewticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTJTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(max_length=20, unique=True)),
                ('learner_email', models.CharField(db_index=True, max_length=255)),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_phone', models.CharField(blank=True, default='', max_length=50)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('programme', models.CharField(blank=True, default='', max_length=255)),
                ('otj_minimum', models.FloatField(default=0)),
                ('otj_completed', models.FloatField(default=0)),
                ('otj_expected', models.FloatField(default=0)),
                ('otj_status', models.CharField(blank=True, default='', max_length=100)),
                ('risk', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='amber', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('hours_logged', 'Hours Logged'), ('support_plan_active', 'Support Plan Active'), ('resolved', 'Resolved')], default='new', max_length=30)),
                ('assigned_owner', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(blank=True, choices=[('called', 'Called'), ('emailed', 'Emailed'), ('hours_submitted', 'Hours Submitted'), ('extra_hours_planned', 'Extra Hours Planned'), ('referred_support', 'Referred to Support'), ('no_action', 'No Action Required')], default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='System', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_otj_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='dashboardbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OTJTicketEvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.otj_evidence_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='api.otjticket')),
            ],
            options={
                'db_table': 'dashboard_otj_evidence',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
