# Generated by Django 4.2.16 on 2026-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mcmticket_mcm_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPATicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(max_length=20, unique=True)),
                ('learner_email', models.CharField(db_index=True, max_length=255)),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_phone', models.CharField(blank=True, default='', max_length=50)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('programme', models.CharField(blank=True, default='', max_length=255)),
                ('coach_name', models.CharField(blank=True, default='', max_length=255)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('risk', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='amber', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('resolved', 'Resolved')], default='new', max_length=30)),
                ('assigned_owner', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(blank=True, choices=[('called', 'Called'), ('emailed', 'Emailed'), ('epa_booked', 'EPA Booked'), ('referred_support', 'Referred to Support'), ('no_action', 'No Action Required')], default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='System', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_epa_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
