# Generated by Django 6.0.3 on 2026-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_epaticket_id_alter_epaticketevidencefile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomSyncState',
            fields=[
                ('source_account', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('zoom_account_id', models.CharField(max_length=128)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('covered_through', models.DateField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('locked_until', models.DateTimeField(null=True)),
                ('lock_token', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'db_table': 'dashboard_zoom_sync_state',
            },
        ),
        migrations.CreateModel(
            name='ZoomPhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(db_index=True, max_length=16)),
                ('zoom_account_id', models.CharField(max_length=128)),
                ('history_id', models.CharField(max_length=255)),
                ('call_id', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(max_length=16)),
                ('caller_number', models.CharField(blank=True, max_length=128)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('caller_user_id', models.CharField(blank=True, max_length=128)),
                ('caller_email', models.CharField(blank=True, max_length=255)),
                ('callee_number', models.CharField(blank=True, max_length=128)),
                ('callee_name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.PositiveIntegerField(null=True)),
                ('raw_result', models.CharField(blank=True, max_length=128)),
                ('result', models.CharField(max_length=32)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_zoom_phone_call',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source_account', 'started_at'], name='zoom_source_started_idx')],
                'constraints': [models.UniqueConstraint(fields=('zoom_account_id', 'history_id'), name='zoom_account_history_unique')],
            },
        ),
    ]
