# Generated by Django 6.0.3 on 2026-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_zoom_phone_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomsyncstate',
            name='recordings_covered_through',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zoomsyncstate',
            name='recordings_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='zoomsyncstate',
            name='recordings_last_success_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ZoomPhoneRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(db_index=True, max_length=16)),
                ('zoom_account_id', models.CharField(max_length=128)),
                ('recording_id', models.CharField(max_length=255)),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('call_log_id', models.CharField(blank=True, max_length=255)),
                ('call_element_id', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(blank=True, max_length=16)),
                ('caller_number', models.CharField(blank=True, max_length=128)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('callee_number', models.CharField(blank=True, max_length=128)),
                ('callee_name', models.CharField(blank=True, max_length=255)),
                ('owner_id', models.CharField(blank=True, max_length=128)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('recording_type', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.PositiveIntegerField(null=True)),
                ('transcript_status', models.CharField(default='pending', max_length=16)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_data', models.JSONField(blank=True, default=dict)),
                ('transcript_error', models.CharField(blank=True, max_length=255)),
                ('transcript_checked_at', models.DateTimeField(null=True)),
                ('transcript_next_retry_at', models.DateTimeField(db_index=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_zoom_phone_recording',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source_account', 'started_at'], name='zoom_recording_started_idx')],
                'constraints': [models.UniqueConstraint(fields=('zoom_account_id', 'recording_id'), name='zoom_account_recording_unique')],
            },
        ),
    ]
