from django.urls import path
from .views import (
    auth_login,
    auth_logout,
    auth_microsoft_login,
    auth_session,
    test_kbc_attendance,
    learner_contact_actions,
    progress_review_summary,
    progress_review_booked_summary,
    booking_review_employer_summary,
    employer_tables_debug,
    fetch_all_coaches_analytics,
    aptem_learners_summary,
    mcr_summary,
    require_marking_summary,
    otj_at_risk_summary,
    kbc_attendance_summary,
    dashboard_bookings,
    dashboard_contact_log,
)

urlpatterns = [
    path("auth/session/", auth_session, name="auth-session"),
    path("auth/login/", auth_login, name="auth-login"),
    path("auth/microsoft-login/", auth_microsoft_login, name="auth-microsoft-login"),
    path("auth/logout/", auth_logout, name="auth-logout"),
    path("test-kbc-attendance/", test_kbc_attendance),
    path("learner-contact-actions/", learner_contact_actions),
    path("progress-review-summary/", progress_review_summary, name="progress-review-summary"),
    path("booking-review-employer-summary/", booking_review_employer_summary, name="booking-review-employer-summary"),
    path("employer-tables-debug/", employer_tables_debug),
    path("coaches/all", fetch_all_coaches_analytics, name="fetch-all-coaches-analytics"),
    path("progress-review-booked/", progress_review_booked_summary, name="progress-review-booked"),
    path("aptem-learners/", aptem_learners_summary, name="aptem-learners-summary"),
    path("mcr-summary/", mcr_summary, name="mcr-summary"),
    path("require-marking/", require_marking_summary, name="require-marking-summary"),
    path("otj-at-risk/", otj_at_risk_summary, name="otj-at-risk-summary"),
    path("kbc-attendance/", kbc_attendance_summary, name="kbc-attendance-summary"),
    path("bookings/", dashboard_bookings, name="dashboard-bookings"),
    path("contact-log/", dashboard_contact_log, name="dashboard-contact-log"),
]
