from django.urls import path
from .views import (
    auth_login,
    auth_logout,
    auth_microsoft_login,
    auth_session,
    test_kbc_attendance,
    learner_contact_actions,
    progress_review_summary,
    progress_review_booked_summary,
    booking_review_employer_summary,
    employer_tables_debug,
    fetch_all_coaches_analytics,
    aptem_learners_summary,
    mcr_summary,
    require_marking_summary,
    otj_at_risk_summary,
    kbc_attendance_summary,
    dashboard_bookings,
    dashboard_contact_log,
    attendance_tickets,
    auto_create_attendance_tickets,
    attendance_ticket_detail,
    attendance_ticket_archive,
    attendance_ticket_files,
    attendance_ticket_file_delete,
    auto_create_pr_tickets,
    pr_tickets,
    pr_ticket_detail,
    pr_ticket_archive,
    pr_ticket_files,
    pr_ticket_file_delete,
    pr_tickets_reset_owners,
    otj_tickets,
    otj_ticket_detail,
    otj_ticket_archive,
    otj_ticket_files,
    otj_ticket_file_delete,
    auto_create_mcm_tickets,
    mcm_tickets,
    mcm_ticket_detail,
    mcm_ticket_archive,
    mcm_ticket_files,
    mcm_ticket_file_delete,
    send_email_proxy,
)

urlpatterns = [
    path("auth/session/", auth_session, name="auth-session"),
    path("auth/login/", auth_login, name="auth-login"),
    path("auth/microsoft-login/", auth_microsoft_login, name="auth-microsoft-login"),
    path("auth/logout/", auth_logout, name="auth-logout"),
    path("test-kbc-attendance/", test_kbc_attendance),
    path("learner-contact-actions/", learner_contact_actions),
    path("progress-review-summary/", progress_review_summary, name="progress-review-summary"),
    path("booking-review-employer-summary/", booking_review_employer_summary, name="booking-review-employer-summary"),
    path("employer-tables-debug/", employer_tables_debug),
    path("coaches/all", fetch_all_coaches_analytics, name="fetch-all-coaches-analytics"),
    path("progress-review-booked/", progress_review_booked_summary, name="progress-review-booked"),
    path("aptem-learners/", aptem_learners_summary, name="aptem-learners-summary"),
    path("mcr-summary/", mcr_summary, name="mcr-summary"),
    path("require-marking/", require_marking_summary, name="require-marking-summary"),
    path("otj-at-risk/", otj_at_risk_summary, name="otj-at-risk-summary"),
    path("kbc-attendance/", kbc_attendance_summary, name="kbc-attendance-summary"),
    path("bookings/", dashboard_bookings, name="dashboard-bookings"),
    path("contact-log/", dashboard_contact_log, name="dashboard-contact-log"),
    path("attendance-tickets/", attendance_tickets, name="attendance-tickets"),
    path("attendance-tickets/auto-create/", auto_create_attendance_tickets, name="attendance-tickets-auto-create"),
    path("attendance-tickets/<int:pk>/", attendance_ticket_detail, name="attendance-ticket-detail"),
    path("attendance-tickets/<int:pk>/archive/", attendance_ticket_archive, name="attendance-ticket-archive"),
    path("attendance-tickets/<int:pk>/files/", attendance_ticket_files, name="attendance-ticket-files"),
    path("attendance-tickets/<int:pk>/files/<int:file_pk>/", attendance_ticket_file_delete, name="attendance-ticket-file-delete"),
    path("pr-tickets/", pr_tickets, name="pr-tickets"),
    path("pr-tickets/auto-create/", auto_create_pr_tickets, name="pr-tickets-auto-create"),
    path("pr-tickets/reset-owners/", pr_tickets_reset_owners, name="pr-tickets-reset-owners"),
    path("pr-tickets/<int:pk>/", pr_ticket_detail, name="pr-ticket-detail"),
    path("pr-tickets/<int:pk>/archive/", pr_ticket_archive, name="pr-ticket-archive"),
    path("pr-tickets/<int:pk>/files/", pr_ticket_files, name="pr-ticket-files"),
    path("pr-tickets/<int:pk>/files/<int:file_pk>/", pr_ticket_file_delete, name="pr-ticket-file-delete"),
    path("otj-tickets/", otj_tickets, name="otj-tickets"),
    path("otj-tickets/<int:pk>/", otj_ticket_detail, name="otj-ticket-detail"),
    path("otj-tickets/<int:pk>/archive/", otj_ticket_archive, name="otj-ticket-archive"),
    path("otj-tickets/<int:pk>/files/", otj_ticket_files, name="otj-ticket-files"),
    path("otj-tickets/<int:pk>/files/<int:file_pk>/", otj_ticket_file_delete, name="otj-ticket-file-delete"),
    path("mcm-tickets/", mcm_tickets, name="mcm-tickets"),
    path("mcm-tickets/auto-create/", auto_create_mcm_tickets, name="mcm-tickets-auto-create"),
    path("mcm-tickets/<int:pk>/", mcm_ticket_detail, name="mcm-ticket-detail"),
    path("mcm-tickets/<int:pk>/archive/", mcm_ticket_archive, name="mcm-ticket-archive"),
    path("mcm-tickets/<int:pk>/files/", mcm_ticket_files, name="mcm-ticket-files"),
    path("mcm-tickets/<int:pk>/files/<int:file_pk>/", mcm_ticket_file_delete, name="mcm-ticket-file-delete"),
    path("send-email/", send_email_proxy, name="send-email-proxy"),
]
